#set_property PACKAGE_PIN P17 [get_ports clkin] 
#set_property PACKAGE_PIN K3 [get_ports clkout] 
#set_property PACKAGE_PIN M1 [get_ports clkt] 
#set_property IOSTANDARD LVCMOS33 [get_ports clkin]
#set_property IOSTANDARD LVCMOS33 [get_ports clkout]
#set_property IOSTANDARD LVCMOS33 [get_ports clkt]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clkin]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports led[0]]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports led[1]]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports led[2]]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports led[3]]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports led[4]]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports led[5]]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports led[6]]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports led[7]]

set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports seg7[0]]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports seg7[1]]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports seg7[2]]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports seg7[3]]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports seg7[4]]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports seg7[5]]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports seg7[6]]

set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports seg_en[0]]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports seg_en[1]]

set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports key_in[3]]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports key_in[2]]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports key_in[1]]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports key_in[0]]

set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33 PULLUP true} [get_ports key_out[3]]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 PULLUP true} [get_ports key_out[2]]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33 PULLUP true} [get_ports key_out[1]]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33 PULLUP true} [get_ports key_out[0]]